---
name: CI

on:
  workflow_dispatch: # Allows manual execution
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job
    permissions:
      contents: write
      packages: write
      security-events: write
    steps:
      - name: Determine CalVer version
        id: calver
        run: echo "CALVER=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Display CalVer
        run: echo "CalVer version ${{ steps.calver.outputs.CALVER }}"

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6

      - name: Build and push
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/caddy-docker-proxy-cloudflare:latest
            ghcr.io/${{ github.actor }}/caddy-docker-proxy-cloudflare:${{ steps.calver.outputs.CALVER }}

      - name: Snyk vulnerability scan
        continue-on-error: true
        uses: snyk/actions/docker@b075801f26076be9bb50521154cafab73f44da0c # master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ghcr.io/${{ github.actor }}/caddy-docker-proxy-cloudflare:${{
            steps.calver.outputs.CALVER }}
          args: --file=Dockerfile

      - name: Replace security-severity undefined or null for license-related findings
        run: |
          sed -i 's/"security-severity": "undefined"/"security-severity": "0"/g' snyk.sarif
          sed -i 's/"security-severity": "null"/"security-severity": "0"/g' snyk.sarif

      - name: Upload Snyk vulnerability scan results to GitHub Code Scanning
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@2892aa5e19bbd11bc0cff5427e3b750a04d9e3c2 # v4
        with:
          sarif_file: snyk.sarif

      - name: Create tag
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.calver.outputs.CALVER }}',
              sha: context.sha
            })
