---
name: CI

on:
  workflow_dispatch: # Allows manual execution
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job
    permissions:
      contents: write
      packages: write
      security-events: write
    steps:
      - name: Determine CalVer version
        id: calver
        run: echo "CALVER=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Display CalVer
        run: echo "CalVer version ${{ steps.calver.outputs.CALVER }}"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6

      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/caddy-docker-proxy-cloudflare:latest
            ghcr.io/${{ github.actor }}/caddy-docker-proxy-cloudflare:${{ steps.calver.outputs.CALVER }}

      - name: Snyk vulnerability scan
        continue-on-error: true
        uses: snyk/actions/docker@9adf32b1121593767fc3c057af55b55db032dc04 # master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ghcr.io/${{ github.actor }}/caddy-docker-proxy-cloudflare:${{
            steps.calver.outputs.CALVER }}
          args: --file=Dockerfile

      - name: Replace security-severity undefined or null for license-related findings
        run: |
          sed -i 's/"security-severity": "undefined"/"security-severity": "0"/g' snyk.sarif
          sed -i 's/"security-severity": "null"/"security-severity": "0"/g' snyk.sarif

      - name: Upload Snyk vulnerability scan results to GitHub Code Scanning
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4
        with:
          sarif_file: snyk.sarif

      - name: Create tag
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.calver.outputs.CALVER }}',
              sha: context.sha
            })
